export const GET_VIDEOGAMES = "GET_VIDEOGAMES"
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL"
export const GET_VIDEOGAME_BY_NAME = "GET_VIDEOGAME_BY_NAME"
export const GET_GENRES = "GET_GENRES"